REM INSERTING into TS_TASKMASTER
Insert into TS_TASKMASTER (TSKID,TSKHOURS,TSKPERCENTCPL,TSKSTARTDATE,TSKENDDATE,PROJECT,TASKDESC) values ('1',20,'0',to_timestamp('10-OCT-10','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('11-OCT-10','DD-MON-RR HH.MI.SSXFF AM'),'Chart','Create req spec');
Insert into TS_TASKMASTER (TSKID,TSKHOURS,TSKPERCENTCPL,TSKSTARTDATE,TSKENDDATE,PROJECT,TASKDESC) values ('2',20,'0',to_timestamp('26-NOV-10','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('30-NOV-10','DD-MON-RR HH.MI.SSXFF AM'),'Chart','Create req spec');
