REM INSERTING into TS_EMP_TIMESHEET
Insert into TS_EMP_TIMESHEET (TSID,EMPID,EMPNAME,TSDATE,TSHRS,TSKID) values (1,'1012','samarjit',to_timestamp('23-NOV-10','DD-MON-RR HH.MI.SSXFF AM'),5,null);
Insert into TS_EMP_TIMESHEET (TSID,EMPID,EMPNAME,TSDATE,TSHRS,TSKID) values (2,'1013','Jam',to_timestamp('23-NOV-10','DD-MON-RR HH.MI.SSXFF AM'),6,null);
